(copy_files ../engine/State.ml)
(copy_files ../engine/TemplateDefinitionTypes.ml)
(copy_files ../engine/Prompt.ml)

(test
 (name state_test)
 (modules State state_test))

(test
 (name prompt_test)
 (modules TemplateDefinitionTypes TemplateRegistry Prompt prompt_test))

(test
 (name processor_test)
 (libraries telomere))
