(test
 (name telomere_smoke)
 (modules telomere_smoke test_support)
 (libraries telomere alcotest)
 (package telomere))

(test
 (name balancer_test)
 (modules balancer_test test_support)
 (libraries telomere alcotest)
 (package telomere))

(test
 (name processor_test)
 (modules processor_test)
 (libraries telomere alcotest)
 (package telomere))

(test
 (name property_test)
 (modules property_test)
 (libraries telomere alcotest qcheck-core qcheck-alcotest yojson)
 (package telomere))
