(test
 (name ribosome_smoke)
 (modules ribosome_smoke test_support)
 (libraries ribosome alcotest)
 (package ribosome))

(test
 (name template_test)
 (modules template_test)
 (libraries ribosome alcotest)
 (package ribosome))

(test
 (name codec_test)
 (modules codec_test)
 (libraries ribosome alcotest yojson)
 (package ribosome))

(test
 (name primitive_codec_test)
 (modules primitive_codec_test)
 (libraries ribosome alcotest yojson)
 (package ribosome))

(test
 (name composite_codec_test)
 (modules composite_codec_test)
 (libraries ribosome alcotest yojson)
 (package ribosome))

(test
 (name template_validate_test)
 (modules template_validate_test)
 (libraries ribosome alcotest)
 (package ribosome))
